/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

/**
 *
 * @author dirief
 */
public class TwoPlayerHangman extends javax.swing.JFrame {

    /**
     * Creates new form TwoPlayerHangman
     */
    public TwoPlayerHangman() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        A = new javax.swing.JButton();
        B = new javax.swing.JButton();
        C = new javax.swing.JButton();
        D = new javax.swing.JButton();
        E = new javax.swing.JButton();
        F = new javax.swing.JButton();
        G = new javax.swing.JButton();
        H = new javax.swing.JButton();
        J = new javax.swing.JButton();
        S = new javax.swing.JButton();
        K = new javax.swing.JButton();
        T = new javax.swing.JButton();
        I = new javax.swing.JButton();
        L = new javax.swing.JButton();
        M = new javax.swing.JButton();
        N = new javax.swing.JButton();
        O = new javax.swing.JButton();
        P = new javax.swing.JButton();
        U = new javax.swing.JButton();
        V = new javax.swing.JButton();
        Q = new javax.swing.JButton();
        R = new javax.swing.JButton();
        A23 = new javax.swing.JButton();
        A24 = new javax.swing.JButton();
        X = new javax.swing.JButton();
        W = new javax.swing.JButton();
        HangmanPic = new javax.swing.JLabel();
        EnterWord = new javax.swing.JLabel();
        GameWordField = new javax.swing.JTextField();
        ConfirmGameWord = new javax.swing.JButton();
        GameWordLine = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        A.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        A.setText("A");
        A.setMargin(new java.awt.Insets(1, 1, 1, 1));

        B.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        B.setText("B");
        B.setMargin(new java.awt.Insets(1, 1, 1, 1));

        C.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        C.setText("C");
        C.setMargin(new java.awt.Insets(1, 1, 1, 1));

        D.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        D.setText("D");
        D.setMargin(new java.awt.Insets(1, 1, 1, 1));

        E.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        E.setText("E");
        E.setMargin(new java.awt.Insets(1, 1, 1, 1));

        F.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        F.setText("F");
        F.setMargin(new java.awt.Insets(1, 1, 1, 1));

        G.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        G.setText("G");
        G.setMargin(new java.awt.Insets(1, 1, 1, 1));

        H.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        H.setText("H");
        H.setMargin(new java.awt.Insets(1, 1, 1, 1));

        J.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        J.setText("J");
        J.setMargin(new java.awt.Insets(1, 1, 1, 1));

        S.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        S.setText("S");
        S.setMargin(new java.awt.Insets(1, 1, 1, 1));

        K.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        K.setText("K");
        K.setMargin(new java.awt.Insets(1, 1, 1, 1));

        T.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        T.setText("T");
        T.setMargin(new java.awt.Insets(1, 1, 1, 1));

        I.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        I.setText("I");
        I.setMargin(new java.awt.Insets(1, 1, 1, 1));

        L.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        L.setText("L");
        L.setMargin(new java.awt.Insets(1, 1, 1, 1));

        M.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        M.setText("M");
        M.setMargin(new java.awt.Insets(1, 1, 1, 1));

        N.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        N.setText("N");
        N.setMargin(new java.awt.Insets(1, 1, 1, 1));

        O.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        O.setText("O");
        O.setMargin(new java.awt.Insets(1, 1, 1, 1));

        P.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        P.setText("P");
        P.setMargin(new java.awt.Insets(1, 1, 1, 1));

        U.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        U.setText("U");
        U.setMargin(new java.awt.Insets(1, 1, 1, 1));

        V.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        V.setText("V");
        V.setMargin(new java.awt.Insets(1, 1, 1, 1));

        Q.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        Q.setText("Q");
        Q.setMargin(new java.awt.Insets(1, 1, 1, 1));

        R.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        R.setText("R");
        R.setMargin(new java.awt.Insets(1, 1, 1, 1));

        A23.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        A23.setText("Z");
        A23.setMargin(new java.awt.Insets(1, 1, 1, 1));

        A24.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        A24.setText("Y");
        A24.setMargin(new java.awt.Insets(1, 1, 1, 1));

        X.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        X.setText("X");
        X.setMargin(new java.awt.Insets(1, 1, 1, 1));

        W.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        W.setText("W");
        W.setMargin(new java.awt.Insets(1, 1, 1, 1));

        HangmanPic.setIcon(new javax.swing.ImageIcon("C:\\Users\\dirief\\Desktop\\Guled\\2PHangmanPics\\start.png")); // NOI18N
        HangmanPic.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 3, true));
        HangmanPic.setMinimumSize(new java.awt.Dimension(36, 44));

        EnterWord.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EnterWord.setForeground(new java.awt.Color(51, 153, 255));
        EnterWord.setText("Player 1: Enter Word for Player 2 to guess!");

        GameWordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 3, true));
        GameWordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameWordFieldActionPerformed(evt);
            }
        });

        ConfirmGameWord.setText("CONFIRM WORD");
        ConfirmGameWord.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 3, true));
        ConfirmGameWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmGameWordActionPerformed(evt);
            }
        });

        GameWordLine.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GameWordLine.setForeground(new java.awt.Color(51, 153, 255));
        GameWordLine.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(F, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(G, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(H, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(I, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(J, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(K, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(M, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(O, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(P, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Q, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(S, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(T, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(U, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(V, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(W, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A24, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A23, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(R, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HangmanPic, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EnterWord, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(GameWordField)
                            .addComponent(ConfirmGameWord)
                            .addComponent(GameWordLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HangmanPic, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EnterWord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GameWordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConfirmGameWord)
                        .addGap(32, 32, 32)
                        .addComponent(GameWordLine)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(G, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(H, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(I, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(J, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(K, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(M, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(O, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(S, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(U, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A23, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A24, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(W, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(V, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GameWordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameWordFieldActionPerformed
 
    }//GEN-LAST:event_GameWordFieldActionPerformed

    private void ConfirmGameWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmGameWordActionPerformed
        String GameWord = GameWordField.getText();
        String EmptyGameWord =("");
        GameWordField.setText("");
        GameWordLine.setText(GameWord);
        
        //Takes game word and covers it in blanks
        for (int i = 0; i < GameWord.length(); i++) {
            if (GameWord.charAt(i) == (' ')) {
                EmptyGameWord += "  ";
            } else {
                EmptyGameWord += "_ ";
            }

        }
       GameWordLine.setText(EmptyGameWord);
    }//GEN-LAST:event_ConfirmGameWordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TwoPlayerHangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TwoPlayerHangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TwoPlayerHangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TwoPlayerHangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TwoPlayerHangman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A;
    private javax.swing.JButton A23;
    private javax.swing.JButton A24;
    private javax.swing.JButton B;
    private javax.swing.JButton C;
    public javax.swing.JButton ConfirmGameWord;
    private javax.swing.JButton D;
    private javax.swing.JButton E;
    private javax.swing.JLabel EnterWord;
    private javax.swing.JButton F;
    private javax.swing.JButton G;
    private javax.swing.JTextField GameWordField;
    private javax.swing.JLabel GameWordLine;
    private javax.swing.JButton H;
    private javax.swing.JLabel HangmanPic;
    private javax.swing.JButton I;
    private javax.swing.JButton J;
    private javax.swing.JButton K;
    private javax.swing.JButton L;
    private javax.swing.JButton M;
    private javax.swing.JButton N;
    private javax.swing.JButton O;
    private javax.swing.JButton P;
    private javax.swing.JButton Q;
    private javax.swing.JButton R;
    private javax.swing.JButton S;
    private javax.swing.JButton T;
    private javax.swing.JButton U;
    private javax.swing.JButton V;
    private javax.swing.JButton W;
    private javax.swing.JButton X;
    // End of variables declaration//GEN-END:variables
}
